# Generated by Django 2.2.5 on 2019-10-12 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('mAddress', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('mEmail', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('mPassword', models.CharField(blank=True, max_length=20, null=True, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='otpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('Otp', models.IntegerField(null=True, verbose_name='otp')),
            ],
        ),
        migrations.CreateModel(
            name='select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(null=True, verbose_name='number')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('Address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('Email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('Password', models.CharField(blank=True, max_length=20, null=True, verbose_name='password')),
                ('otpu', models.IntegerField(null=True, verbose_name='otp')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('vno', models.CharField(blank=True, max_length=20, null=True, verbose_name='vehicle No.')),
                ('fromplace', models.CharField(blank=True, max_length=20, null=True, verbose_name='From place')),
                ('toplace', models.CharField(blank=True, max_length=20, null=True, verbose_name='To place')),
                ('vTime', models.DateTimeField(null=True, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberv', models.CharField(blank=True, max_length=20, null=True, verbose_name='vehicle no.')),
                ('fromplace', models.CharField(blank=True, max_length=20, null=True, verbose_name='From place')),
                ('toplace', models.CharField(blank=True, max_length=20, null=True, verbose_name='To place')),
                ('oEmail', models.EmailField(max_length=254, null=True, verbose_name='Reciever Email')),
                ('uname', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('charge', models.FloatField(null=True, verbose_name='charge')),
                ('oTime', models.DateTimeField(null=True, verbose_name='time')),
                ('weight', models.IntegerField(null=True, verbose_name='weight')),
                ('r_pn', models.IntegerField(null=True, verbose_name='phonenumber')),
                ('m_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.media')),
                ('s_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.user')),
            ],
        ),
    ]
