# Generated by Django 2.2.5 on 2019-10-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_media_mcont'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='motpu',
            field=models.IntegerField(null=True, verbose_name='otp'),
        ),
    ]
