# Generated by Django 2.2.5 on 2019-10-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_media_motpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='reach',
            field=models.CharField(max_length=30, null=True, verbose_name='reach'),
        ),
    ]
