# Generated by Django 2.2.5 on 2019-10-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_order_v_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='v_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.vehicle'),
        ),
    ]
