# Generated by Django 2.2.5 on 2019-10-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_vehicle_v_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='v_name',
        ),
        migrations.AddField(
            model_name='media',
            name='v_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.vehicle'),
        ),
    ]
