# Generated by Django 2.2.5 on 2019-10-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191012_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='v_name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='v_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.media'),
        ),
    ]
